### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by zanella** [devopsbq/nomad-client#4]
Hey,

I didn't find your lib and ended up writing an eerily similar one (https://github.com/zanella/nomad-api), but since you guys seem to use it (nomad) it makes no sense to keep an unmaintained dup, so, I'll just point to your repo.

There are a bunch of mock tests done, but I'm unsure about the value gained for you guys from using it, since having a real nomad running would be far more trustable (like having a docker-compose called for bringing up nomad or something like that for tests)

Cheers

**Comment by jorgemarey** [comment]
Hi! I don't know if we'll be able to keep this up to date, we'll stop using it for a while. So, maybe it's better for you to use your own repo or make a fork of this one.

**Comment by zanella** [comment]
Ah, I see..., well, then I guess time will tell if any of them gets used, cheers.
