### ISSUE TITLE
Maven public repo

### ISSUE THREAD

**Issue by hgontijo** [devopsbq/nomad-client#5]
Hi,

Is the maven artifact published on a public maven repo?

Thanks.

**Comment by jorgemarey** [comment]
Hi! We don't have it published on any public repo at the moment. I could try and submit a request to sonatype, but it could take a few days. In any case, I don't know if we can keep this up to date... If you are thinking on using this, maybe it's better to make a fork and work on that.

**Comment by hgontijo** [comment]
Thanks for clarifying and also for open sourcing the code. I'll let you know If I decide to fork and publish it to a public repo. Could you please confirm the project license is Apache License 2.0?

**Comment by jorgemarey** [comment]
Yep! It's Apache License 2.0

**Comment by zanella** [comment]
@hgontijo (https://github.com/zanella/nomad-api) is up in maven central already, feel free to poke around there as well /shameless plug

**Comment by hgontijo** [comment]
Hi @zanella, thanks for pointing that out. In fact, I already started my development based on this repo and I think I will stick with it (with minor fixes so far). Your repo has a lot of tests though, which it's something missing in here. For now, I forked this project and I'll submit the changes in there. Closing this ticket since there's no plan for a maven repo.
